### PR TITLE
Default value when sequence are missing

### PR DESCRIPTION
**Pull request by bryan-brancotte**
Proposition to fixe errors message we get such like
```log
Use of uninitialized value in length at /usr/local/lib/BIGSdb/Plugins/GenomeComparator.pm line 2491.
Use of uninitialized value in length at /usr/local/lib/BIGSdb/Plugins/GenomeComparator.pm line 945.
Use of uninitialized value in length at /usr/local/lib/BIGSdb/Plugins/GenomeComparator.pm line 984.
```

credits to https://research.pasteur.fr/en/member/sophie-creno/

### CODE REVIEW

**Comment by kjolley** [comment]
Could you check out b2e653f as I think this fixes it better?:

The length variable in lines 945 and 984 should only be used when analyzing by reference (where the sequence should always be available) so I've moved their assignment.

The length variable in line 2491 should be an empty string when sequence is unavailable, not zero, since this is the output to a text file (field is left blank whereas a zero is wrong).

I cannot see why you would get an error at line 1773 as this is only called when you're analyzing by a reference, and by definition you will have a sequence.

**Comment by bryan-brancotte** [comment]
Closing thanks to https://github.com/kjolley/BIGSdb/commit/b2e653ffeb928f308f65dcb8b7e07f7070101ed8

**Comment by kjolley** [comment]
Thanks. Weird that I wasn't getting those warnings logged as I should have been. I wonder if this is due to a difference in the Perl versions we're running.

**Comment by kjolley** [comment]
Oops. Fixed last commit with e2fdd84.

**Comment by bryan-brancotte** [comment]
These logs are not from any log files, they appears when we run bigsjobs.pl from a crontask. These warnings are only printed to the terminal and as we run it from a crontask with MAILTO defined we get these output.

**Pull request closed without merging**
